name: deploying

on:
    push:
        branches:
            - main
env:
  SSH_KEY: ${{secrets.SSH_KEY}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_HOST1: ${{secrets.SSH_HOST1}}
  SSH_HOST2: ${{secrets.SSH_HOST2}}

jobs:
    check:
        runs-on: Checkout Repositry
        steps:
          - name: Checkout Repositry
            uses: actions/checkout@v4
    deploy:
        runs-on: self-hosted1
        steps:
          - name: Deploying to server 1
            run: |
              echo "$SSH_KEY" > mKey.pem
              chmod 600 mKey.pem
              ssh -i myKey2.pem $SSH_USER@$SSH_HOST1 
              cd capstone_Twaq
              git pullhttps://github.com/Pep15/capstone_Twaq.git
              docker compose up -d --build
          - name: Deploying to server 2
            run: |
              echo "$SSH_KEY" > mKey.pem
              chmod 600 mKey.pem
              ssh -i mKey.pem $SSH_USER@$SSH_HOST2 
              cd capstone_Twaq
              git pullhttps://github.com/Pep15/capstone_Twaq.git
              docker compose up -d --build
