name: Build and Push

on:
  workflow_call:
    inputs:
      docker_username:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSOWRD }}  # Ensure the secret name is correct

      - name: Build Docker image
        run: |
           docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

      - name: Push Docker image
        run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest