name: CD

on:
  push:
  # workflow_run: 
  #   workflows: ["CI"]
  #   types:
  #     - completed    

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_USER: ${{ secrets.SSH_USERNAME }}
  SSH_HOST1: ${{ secrets.HOST1 }}
  SSH_HOST2: ${{ secrets.HOST2 }}

jobs:
  deploy1:
    runs-on: self-hosted
    steps:
      - name: Deploying to server 1
        run: |
          echo "${{ secrets.SSH_KEY }}" > mKey1.pem
          chmod 600 mKey1.pem
          ssh -i mKey1.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST1 }} << 'EOF'
          set -e
          cd /capstone_Twaq
           git config pull.ff
          git pull https://github.com/Pep15/capstone_Twaq.git
          docker compose up -d --build
          rm -f mKey.pem
          EOF
  deploy2:
    runs-on: self-hosted
    steps:
      - name: Deploying to server 2
        run: |
          echo "${{ secrets.SSH_KEY }}" > mKey2.pem
          chmod 600 mKey2.pem
          ssh -i mKey2.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST2}} << 'EOF'
          set -e
          cd /capstone_Twaq
           git config pull.ff
          git pull https://github.com/Pep15/capstone_Twaq.git
          docker compose up -d --build
          rm -f mKey.pem
          EOF