name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_username: ${{ secrets.DOCKER_USERNAME }}